[preface]
image:https://img.shields.io/badge/Download-Release%20{viglet-version}-blue?style=for-the-badge&logo=OpenJDK[link="https://viglet.com/shio/download/"]
image:https://img.shields.io/github/license/openviglet/shio.svg?style=for-the-badge&logo=Apache["License"]
image:https://img.shields.io/github/last-commit/openviglet/shio.svg?style=for-the-badge&logo=java)[GitHub last commit]
image:https://img.shields.io/github/actions/workflow/status/openviglet/shio/build.yml?branch=2025.1&style=for-the-badge&logo=GitHub[link="https://github.com/openviglet/shio/actions/workflows/build.yml"]
image:https://img.shields.io/badge/Sonar-Code%20Quality-brightgreen?style=for-the-badge&logo=SonarCloud[link="https://sonarcloud.io/project/overview?id=viglet_shio"]
------

**Viglet Shio CMS** - Model Content, use GraphQL and Create Site using Javascript with Native Cache and Search.

Shio (pronounced [strong/ʃiː/ weak/ʃɪ/ o])

**If you'd like to contribute to Viglet Shio, be sure to review the [contribution
guidelines](CONTRIBUTING.md).**

**We use [GitHub issues](https://github.com/ShioCMS/shio/issues) for tracking requests and bugs.**

# Installation

## Pre-reqs
1. Install Java 14
2. Install Git Client
3. Install NPM
4. Install Angular CLI
```shell
$ npm install -g @angular/cli
```

## Download

```shell
$ git clone https://github.com/ShioCMS/shio.git
$ cd shio
```

## Deploy 

### 1. Runtime

Use Gradle to execute Shio CMS, without generate jar file.

```shell
$ ./mvnw spring-boot:run
```


### 2. Or Generate JAR File

Use Gradle to generate Shio CMS executable JAR file.

```shell
$ ./mvnw package
```

#### 2.1 Run

To run Shio CMS executable JAR file, just execute the following line:

```shell
$ java -jar build/libs/viglet-shio.jar
```

## Viglet Shio CMS
* Administration Console: [http://localhost:2710](http://localhost:2710).

> login/password: admin/admin

* Sample Site: [http://localhost:2710/sites/viglet/default/en-us](http://localhost:2710/sites/viglet/default/en-us).
